Add deobfuscation args to jadx
APKLab/APKLab pull request #117
Opened 2021-02-07 21:24 UTC by psolyca

As the title says.

Add all options for deobfuscation in the drop-down menu when opening an APK.

2021-02-08 03:54 UTC, Surendrajat requested changes
Thanks for this PR @psolyca. I like the idea of providing more options to control the output behavior, but I have some UX related concerns as I've commented.

2021-02-08 03:54 UTC, Surendrajat commented on src/quick-pick.util.ts
> +            label: "--deobf-min",
This will not work as it needs an extra input for integer value which is not implemented. I'm not yet sure of the correct UX for all these inputs which will make the user jump through multiple hoops just to open an APK. Maybe a webview with all options or maybe in settings. Suggestions are welcome.

2021-02-08 03:54 UTC, Surendrajat commented on src/quick-pick.util.ts
> +            label: "--deobf-max",
Same as above. Can be left out for now.

2021-02-08 03:54 UTC, Surendrajat commented on src/quick-pick.util.ts
> +            label: "decompile_java",
While I understand the reason, I think we should not move this option after apktool args as this is a major feature, and it's not enabled by default.
You can append the tool name to args for easy filtering, like `--deobf (jadx)` and `--no-res (apktool)` instead.

2021-02-08 03:59 UTC, Surendrajat commented on src/quick-pick.util.ts
> +            label: "--deobf-use-sourcename",
Just curious: what does this option do? I tried decompiling with and without it but didn't notice the difference.

2021-02-08 08:33 UTC, psolyca commented on src/quick-pick.util.ts
> +            label: "--deobf-min",
I can remove them as I do not use them, it was to complete the feature.
I could reintroduced them when I understand how to code in for VSCode ^^;

2021-02-08 08:33 UTC, psolyca commented on src/quick-pick.util.ts
> +            label: "--deobf-max",
Same comment.

2021-02-08 08:37 UTC, psolyca commented on src/quick-pick.util.ts
> +            label: "--deobf-use-sourcename",
Haha it was to complete the feature.
I have tried the option yesterday and... like you, I do not see the difference.
Also, with the option `--deobf-rewrite-cfg` I did not see any files where mapping is done.
So I will keep only the main option `--deobf`.
It was a good attention ^^

2021-02-08 08:38 UTC, psolyca commented on src/quick-pick.util.ts
> +            label: "decompile_java",
I will try ^^
I am not a TypeScript nor Javascript coder :p

2021-02-08 08:52 UTC, Surendrajat commented on src/quick-pick.util.ts
> +            label: "--deobf-use-sourcename",
Maybe @skylot himself can help us out here :)
For now, yeah go ahead with `--deobf` alone and check for it just like `decompile_java`.

2021-02-08 08:52 UTC, Surendrajat commented on src/quick-pick.util.ts
> +            label: "decompile_java",
As written in other comment, let's just keep `--deobf` for now and move `decompile_java` to top. We will add other options too once we figure out a proper place to fit them.

2021-02-08 13:54 UTC, skylot commented on src/quick-pick.util.ts
> +            label: "--deobf-use-sourcename",
`--deobf-use-sourcename` - will use source file name (origin file name of the class) as class name if possible. This name also added as a class comment `/* compiled from: ... */`. Unfortunately, all obfuscators change this value, sometimes use same name for all classes or even put garbage data in it, so in most cases it is not very helpfull.

`--deobf-rewrite-cfg` - will ignore and overwrite deobfuscation name mapping file.

2021-02-08 15:03 UTC, Surendrajat commented on src/quick-pick.util.ts
> +            label: "--deobf-use-sourcename",
Thanks for the clarification, @skylot. :)

2021-02-09 03:54 UTC, Surendrajat requested changes
Looks good. One small change needed and we can merge it.

2021-02-09 03:54 UTC, Surendrajat commented on src/interface.ts
> +                    jadxArgs = args.splice(jadxOptionsIndex);
Only remove one item here. We might forget it when we add something after it.
```suggestion
                    jadxArgs = args.splice(jadxOptionsIndex, 1);
```

2021-02-09 08:01 UTC, psolyca commented on src/interface.ts
> +                    jadxArgs = args.splice(jadxOptionsIndex);
If you want.
I was in the idea to keep args separated, first args for `apktool` then args for `jadx`.
Then without specifing this number we take by default all options after `--deobf` option for `jadx`.
If we add more options for `jadx` we do not have to forget to change this value.
Just my thought.

2021-02-09 10:03 UTC, Surendrajat approved these changes

2021-02-09 10:04 UTC, Surendrajat commented
Thank you for your contribution!

2021-02-09 10:04 UTC, merged