refactor project src dir structure
APKLab/APKLab pull request #122
Opened 2021-02-19 18:14 UTC by Surendrajat

This will help with better organization/isolation of code-base for various tools and improves readability/consistency.

2021-03-02 15:32 UTC, amsharma44 requested changes

2021-03-02 15:32 UTC, amsharma44 commented on src/tools/apk-mitm.ts
Since we're exporting a namespace at top level, let's continue the same pattern and export ```applyMitmPatches``` function inside a namespace.

2021-03-02 15:32 UTC, amsharma44 commented on src/tools/git.ts
> + */
Same here, export functions wrapped inside a namespace.

2021-03-02 15:32 UTC, amsharma44 commented on src/utils/executor.ts
> +interface ProcessOptions {
Can we move ```ProcessOptions``` to a different location? Maybe in ```constants.ts``` or a separate file like ```interfaces.ts``` . Does it make sense to you?

2021-03-02 16:35 UTC, Surendrajat commented on src/tools/apk-mitm.ts
That's good idea. Will do it.

2021-03-02 16:36 UTC, Surendrajat commented on src/utils/executor.ts
> +interface ProcessOptions {
Makes sense. However, these are types (one or two more in downloader.ts etc.) so maybe I'll create a types.ts.

2021-03-05 05:51 UTC, Surendrajat commented on src/utils/executor.ts
> +interface ProcessOptions {
@amsharma44 so I looked around some projects and the way to maintain `types.ts` has a downside of imports and all when the types are only being referenced in a single file, and it is generally recommended keeping such types near references. We can use `types.ts` when we have some global types but for now I think we're good.

2021-03-05 12:43 UTC, amsharma44 approved these changes

2021-03-05 12:43 UTC, merged