Add 'show inconsistent code' arg to jadx
APKLab/APKLab pull request #127
Opened 2021-04-06 22:01 UTC by psolyca

Add option to 'show bad code' during decompilation in the drop-down menu when opening an APK.

This option avoid "throw new UnsupportedOperationException("Method not decompiled: blablabla"
Code is not clean but it is better than nothing to RE.

2021-04-07 11:20 UTC, Surendrajat requested changes
@psolyca Thanks for the PR. I appreciate it.
However, due to some ugly hack we used earlier(L:54 & L:58), this option will fail to work in case the user does not select the `--deobf (jadx)` option. Could you please fix that?

2021-04-07 18:26 UTC, psolyca commented
Ho sorry, I didn't see that as I use both options.
Will have a look.

2021-04-09 13:55 UTC, psolyca commented
@Surendrajat Is this ok for you this way ?
It is maybe more "complexe" but more open to any changes later in `quick-pick` menu. No hardcoded values.

2021-04-09 16:20 UTC, Surendrajat requested changes
@psolyca Looks much better and works too. Thanks.
I've few small comments if you can address then we can merge it.

2021-04-09 16:20 UTC, Surendrajat commented on src/utils/quick-picks.ts
> +            detail: "show inconsistent code (incorrectly decompiled)",
```suggestion
            detail: "Show inconsistent code (incorrectly decompiled)",
```

2021-04-09 16:20 UTC, Surendrajat commented on src/interface.ts
> +                const argsIndex = quickPickItems.map<string | undefined>(
Index might reflect the intent but not super clear right away.
```suggestion
                const argDescriptions = quickPickItems.map<string | undefined>(
```

2021-04-09 16:39 UTC, psolyca commented on src/interface.ts
> +                const jadxOptionsNumber = argsIndex.filter(
```suggestion
                const decompileJavaIndex = argDescriptions.indexOf("[Use Jadx]");
                const quarkAnalysisIndex = argDescriptions.indexOf(
                    "[Use Quark-Engine]"
                );
                const jadxOptionsIndex = argDescriptions.indexOf("jadx");
                const jadxOptionsNumber = argDescriptions.filter(
```
For the record

2021-04-11 03:05 UTC, Surendrajat approved these changes

2021-04-11 03:05 UTC, merged